import { jsPDF } from "jspdf";

function generatePDF(analysis) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const margin = 22;
  const contentWidth = pageWidth - margin * 2;

  let y = 25;

  // ---------------- PAGE BORDER ----------------

  function drawPageBorder() {
    doc.setDrawColor(170);
    doc.setLineWidth(0.5);

    doc.rect(
      10,
      10,
      pageWidth - 20,
      pageHeight - 20
    );
  }

  drawPageBorder();

  // ---------------- TITLE ----------------

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text(
    "Resume Audit Report",
    pageWidth / 2,
    y,
    { align: "center" }
  );

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(
    `Generated on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    y,
    { align: "center" }
  );

  y += 10;

  doc.setDrawColor(180);

  doc.line(
    margin,
    y,
    pageWidth - margin,
    y
  );

  y += 18;

  // ---------------- ATS ----------------

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);

  doc.text(
    "ATS SCORE",
    pageWidth / 2,
    y,
    { align: "center" }
  );

  y += 16;

  doc.setFontSize(34);

  doc.text(
    `${analysis.ats_score}%`,
    pageWidth / 2,
    y,
    { align: "center" }
  );

  y += 14;

  let verdict = "Needs Improvement";

  if (analysis.ats_score >= 80) {
    verdict = "Excellent";
  } else if (analysis.ats_score >= 60) {
    verdict = "Good Match";
  }

  doc.setFontSize(15);

  doc.text(
    verdict,
    pageWidth / 2,
    y,
    { align: "center" }
  );

  y += 14;

  doc.line(
    margin,
    y,
    pageWidth - margin,
    y
  );

  y += 12;

  // ---------------- SUMMARY ----------------

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);

  doc.text(
    "AI SUMMARY",
    margin,
    y
  );

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const summary = doc.splitTextToSize(
    analysis.summary,
    contentWidth
  );

  doc.text(
    summary,
    margin,
    y
  );

  y += summary.length * 6 + 10;

  doc.line(
    margin,
    y,
    pageWidth - margin,
    y
  );

  y += 10;

  // ---------------- HELPER ----------------

  function addSection(title, items) {

    if (y > 245) {
      doc.addPage();

      drawPageBorder();

      y = 25;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);

    doc.text(
      title,
      margin,
      y
    );

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    items.forEach((item) => {

      const lines = doc.splitTextToSize(
        item,
        contentWidth - 10
      );

      doc.text(
        "•",
        margin,
        y
      );

      doc.text(
        lines,
        margin + 7,
        y
      );

      y += lines.length * 6 + 5;

      if (y > 260) {

        doc.addPage();

        drawPageBorder();

        y = 25;
      }

    });

    y += 3;

    doc.setDrawColor(180);

    doc.line(
      margin,
      y,
      pageWidth - margin,
      y
    );

    y += 10;
  }

  // ---------------- SECTIONS ----------------

  addSection(
    "STRENGTHS",
    analysis.strengths
  );

  addSection(
    "WEAKNESSES",
    analysis.weaknesses
  );

  addSection(
    "MISSING SKILLS",
    analysis.missing_skills
  );

  addSection(
    "RECOMMENDATIONS",
    analysis.improvements
  );

  // ---------------- FOOTER ----------------

  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {

    doc.setPage(i);

    doc.setFontSize(10);

    doc.setDrawColor(180);

    doc.line(
      margin,
      280,
      pageWidth - margin,
      280
    );

    doc.text(
      "Generated by CareerLens AI",
      pageWidth / 2,
      286,
      {
        align: "center"
      }
    );

    doc.text(
      `Page ${i} of ${pages}`,
      pageWidth / 2,
      292,
      {
        align: "center"
      }
    );

  }

  doc.save("Resume_Audit_Report.pdf");
}

export default generatePDF;